version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: emailservice Build and push Docker image
          command: |
            sudo docker build -t junaidk/emailservice:${CIRCLE_BUILD_NUM} .
            sudo docker login -u "$username" -p "$password"
            sudo docker push junaidk/emailservice:${CIRCLE_BUILD_NUM}
